### ISSUE TITLE
This isn't an issue but i can't find a way to suggest...

### ISSUE THREAD

**Issue by Xeroxytgt** [PowerOfUniverse/Surviv.io-Cheats#12]
Maybe add a way to stream snipe streamers or be able to join games with other hackers or know when theres a hacker in the game, maybe chat in the menu would be possible?

**Comment by alexvornoffice** [comment]
If you want - you can play with me in a team, how to contact you? :)

**Comment by 00petar00** [comment]
Maybe the dev could start a discord channel or something, seen people ask for others to team up before.

**Comment by PowerOfUniverse** [comment]
I can create a chat. In my free time I will look for some free vps server.

**Comment by 00petar00** [comment]
> To add a chat, you need a server (eg with linux).

Discord servers are free, you should look into it, that's the reason it is so popular today.

**Comment by PowerOfUniverse** [comment]
I was thinking more about separate channels for each server. There would be a public chat in the menu. That is why discord is a weak solution.

**Comment by PowerOfUniverse** [comment]
I can use a different solution. But the maximum number of messages per day is 150,000.

**Comment by 00petar00** [comment]
Don't see why there is a problem, having multiple channels on discord works fine, that way also everyone could be together so even though we play on different servers we could gather there.

To be honest i don't really mind if you have anything else instead of discord, its just that is free. I would like to be able to play with some of the players that are using the extension.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/projects/1
