### ISSUE TITLE
Toggle-able autofire with right click (or other key)

### ISSUE THREAD

**Issue by holidaynights** [PowerOfUniverse/Surviv.io-Cheats#25]
Constant autofire and trigger bot being on is an easy way to get the bot lots of negative attention and it's very obvious you're 'hacking.' 

The extensions that get the greatest results and longevity allow you to 'activate' the autoaim for the duration you're holding a key down (e.g. right click)

**Describe the solution you'd like**
Toggle-able autofire with right click (or other key)

**Additional context**
Lots of great features tied to the autofire (like seeing what gear the enemy has) but can't be used since I never have autoaim on since it's way too obvious you're aimbotting with the hard snapping to the enemy players even with minimum 1 restriction. I love everything else about the extension, though, don't get me wrong! Discovering lots of neat features packed in here. :-)

**Comment by alexvornoffice** [comment]
Maybe color the lines to players to other color:
example: **red line color** - you can not shot them because of the collisions
**green line color** towards the enemies - you can hit them, no collisions...

So we disable autofire completely ( because we get a lot of attention !!! ), and we shot normally or,
the autofire work whens we press a button (to activate), and/or we press left click to shot.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/projects/1
I will add it in my spare time, only on the right mouse button.
